### ISSUE TITLE
Latest model is deleted?

### ISSUE THREAD

**Issue by ishowta** [chenxwh/cog-whisper#12]
https://replicate.com/openai/whisper/versions

latest model (`23241e5731b44fcb5de68da8ebddae1ad97c5094d24f94ccb11f7c1d33d661e2`) is not found on the web and I got a few error with message `Model (version:23241e5731b44fcb5de68da8ebddae1ad97c5094d24f94ccb11f7c1d33d661e2) not found, defaulting to 30414ee7c4fffc37e260fcab7842b5be470b9b840f2b608f5baa9bbef9a259ed`.
Parameters are different between these versions and will not work if fallback is done.
Is this a replicate issue?

![2022-12-16_134801](https://user-images.githubusercontent.com/7393198/208024585-7b874151-feea-4759-bc5a-cea7fb8201d0.png)

**Comment by chenxwh** [comment]
Seems some colleagues deleted the latest version due to the issue raised https://github.com/chenxwh/cog-whisper/issues/11 here? 

I pushed v2 here if you like to try while I investigate the reason for the slow speed: https://replicate.com/cjwbw/whisper

**Comment by ishowta** [comment]
Thank you for the information.
Since it is version controlled, I thought it would have been better to revert the commit and publish in a new version.

**Comment by chenxwh** [comment]
Previous version is under main branch anyway
________________________________
