### ISSUE TITLE
Translated subtitles

### ISSUE THREAD

**Issue by SonofUgly** [chenxwh/cog-whisper#6]
If translate to English is set, the only translation output is in a block of text even if transcription is set to output in subtitle format. The subtitle transcription is in the audio file's native language, but it should also be translated.

Also just a small aside, but there should be a blank line in between subtitle lines:
| Output  | Correct |
| ------------- | ------------- |
| 156<br>00:06:03,000 --> 00:06:04,000<br>そのトーンで<br>157<br>00:06:04,000 --> 00:06:05,000<br>いやうまい | 156<br>00:06:03,000 --> 00:06:04,000<br>そのトーンで<br><br>157<br>00:06:04,000 --> 00:06:05,000<br>いやうまい  |

**Comment by playgroundjohn** [comment]
Agree, any info on this?

**Comment by chenxwh** [comment]
added blank lines in the new pushed version, thanks for the suggestion!
